// Generated by CoffeeScript 1.7.1
var canvas, ctx, drawRect, init, mouseMoveListener, start;

canvas = null;

ctx = null;

window.onload = function() {
  init();
  start();
  return void 0;
};

init = function() {
  canvas = document.getElementById("can");
  ctx = canvas.getContext('2d');
  canvas.onmousemove = mouseMoveListener;
  return void 0;
};

start = function() {
  document.addEventListener("mousemove", drawRect());
  return void 0;
};

drawRect = function() {
  ctx.beginPath();
  ctx.fillRect(30, 30, 100, 50);
  return void 0;
};

mouseMoveListener = function(e) {
  var rect;
  rect = e.target.getBoundingClientRect;
  console.log(e.clientX);
  console.log(e.clientY);
  return void 0;
};
