// Generated by CoffeeScript 1.7.1
var canvas, ctx, drawRect, init, start;

canvas = null;

ctx = null;

window.onload = function() {
  init();
  start();
  return void 0;
};

init = function() {
  canvas = document.getElementById("can");
  return ctx = canvas.getContext('2d');
};

start = function() {
  document.addEventListener("mousemove", drawRect());
  return void 0;
};

drawRect = function() {
  ctx.beginPath();
  ctx.fillRect(30, 30, 100, 50);
  return void 0;
};
